### ISSUE TITLE
Not possible to scp from infix

### ISSUE THREAD

**Issue by mattiaswal** [kernelkit/infix#173]
From my PC I try to initiate a SCP from infix.
lazzer@tollan ~/Documents/addiva/infix/infix-x86_64 (main)$ scp admin@192.168.100.1:/tmp/data3 /tmp/
admin@192.168.100.1's password: 
scp -f /tmp/data3
Error:
Illegal command

**Comment by troglobit** [comment]
Default login shell for admin user is clish, so that won't work currently.  Needs a magic redirect or something to a shell.

**Comment by terefang** [comment]
why not have "proftpd" in ssh/sftp mode runnig on port 2222 ?

**Comment by troglobit** [comment]
That's also a possibility, but I think we're more likely to go for sftp using openssh subsystem.

**Comment by terefang** [comment]
that might also cause problems because i know at least one client (WinScp maybe others), that will fallback to scp based filetransfers because of performance reasons

**Comment by wkz** [comment]
This will be fixed by #266

**Comment by troglobit** [comment]
Nice take on this one, @wkz, very appreciated!
