### ISSUE TITLE
BUG: possible to set bridge-port br0 on bridge br0

### ISSUE THREAD

**Issue by mattiaswal** [kernelkit/infix#177]
root@infix-00-00-00:/config/interfaces/interface/br0/> set bridge-port bridge br0
root@infix-00-00-00:/config/interfaces/interface/br0/> leave 
find: /run/net/3/dag/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0/br0: Too many levels of symbolic links

**Comment by mattiaswal** [comment]
Tried to fix without success:
diff --git a/src/confd/yang/infix-if-bridge@2023-08-21.yang b/src/confd/yang/infix-if-bridge@2023-08-21.yang
index e56e3b3..7588d85 100644
--- a/src/confd/yang/infix-if-bridge@2023-08-21.yang
+++ b/src/confd/yang/infix-if-bridge@2023-08-21.yang
@@ -148,6 +148,7 @@ submodule infix-if-bridge {
 
         leaf bridge {
           type if:interface-ref;
+         when "!derived-from-or-self(../../if:type,'ianaift:bridge')";
           must "deref(.)/../bridge" {
             error-message "Must refer to a bridge interface.";
           }

**Comment by troglobit** [comment]
This and the nasty klish bugs we can start working on after the two big customer releases in November.
