### ISSUE TITLE
Handle breaking changes to YANG models

### ISSUE THREAD

**Issue by wkz** [kernelkit/infix#178]
In an AFK discussion, the following question was brought up:

> Sooner or later, we will have to make breaking changes to YANG models that will cause `confd` to reject old configs. How should we handle that?

Some ideas:

- `confd` should only care about the current YANG models belonging to any given version of Infix.
- We can create special text transformers that translate a valid `infix-x.y.z` config to a valid `infix-x+1.y.z` config, these can be simple scripts that run a few `jq(1)` pipelines. 
- The transformers can be stacked as infix evolves to support going from any config version to the present.
- The original config should always be preserved, so that a user can audit the diff.
- The config files need a version field, so that we know the starting point in the transformer stack.

### Config File Versioning

To keep the version information somewhat out-of-band from the actual configuration data, we should look at the possibility of adding it as a [metadata annotation](https://datatracker.ietf.org/doc/html/rfc7952#section-3.1).

Sketch:

    module infix-system {
      import ietf-yang-metadata {
        prefix "md";
      }
      md:annotation compatible {
        type string;
        description
          "Specifies the operating system which this configuration
           is compatible with. When a generated by the system
           itself, it is set to the concatenation of ID and
           VERSION_ID, as specified in /etc/os-release, joined by
           a hyphen.";
      }
    }

Example:

```js
{
    "ietf-system:system": {
        "@": {
            "infix-system:compatible": "infix-v24.06.0"
        }
    }
}
```

Having the OS name in addition to the version could potentially enable one OS to extract general settings from another, while ignoring OS-specific configuration.

### Backup/Restore

- Add `restore-config` RPC that will parse out the metadata and run the required transforms before feeding it to `sysrepo`.
- If we ever start to version config's on the device, provide a `backup-config` RPC that can fetch older versions.

**Comment by troglobit** [comment]
PR https://github.com/kernelkit/infix/pull/324 shows an alternative/complementary route to take for breaking changes:

  1. Mark old setting as `deprecated` or `obsolete` (needs planning ahead)
  2. Introduce new setting replacement, used only if old setting does not exist

**Comment by troglobit** [comment]
@wkz unfortunately it appears that sysrepo does not support annotations: sysrepo/sysrepo#2462 The bug report has a few years to it, but this seems to be still the case.  so I'll go ahead and add a plain config augment with a discouraging description instead.

**Comment by troglobit** [comment]
Break out into own model, infix-version.yang
