### ISSUE TITLE
Failed to copy factory-config to startup-config

### ISSUE THREAD

**Issue by ahmkar94** [kernelkit/infix#259]
Issue
--------
The command:
 `copy factory-config startup-config`
 fails to copy factory configuration to `/cfg/startup-config.cfg`

Workaround
----------------
Run the commands in the following order:
`copy running-config startup-config`
`copy factory-config startup-config`
**Copying successful**

**Comment by troglobit** [comment]
Just noticed a similar issue on the NanoPi R2S, tab completing `copy running-config sta<TAB>` did not work. Typing it in manually though did work, however.

Both `copy` and tab completion are part of `src/klish-plugin-infix`.  The tab completion function, `infix_datastore()` as well as logs to stderr, which I believe is wrong.  klishd parses and mangles the output from these callbacks, so we should probably rewrite the logging functions to use `syslog()` instead as an attempt to get to the bottom of this issue.

**Comment by troglobit** [comment]
- Original bug report reproduced
 - Root cause found

Fix pending on `container-basic` branch.
