### ISSUE TITLE
Setting hostname is adding quotation marks to the DHCP request.

### ISSUE THREAD

**Issue by minexn** [kernelkit/infix#283]
Manually setting the hostname in the DHCP request, and quotation marks are sent to the DHCP server.

<img width="248" alt="DHCP hostname" src="https://github.com/kernelkit/infix/assets/129349368/629903a1-306b-4173-9214-a8556134f440">

Config

```
set dhcp-client client-if eth0
set dhcp-client client-if eth0 option hostname value infix-r2s-1
```
This can be seen in the udhcpc process.

`udhcpc -f -p /run/dhcp-eth0.pid -t 10 -T 3 -A 10 -a1000 -S -R -x hostname:"infix-r2s-1" -i eth0 -V Infix v23.11.0-121-g051658d-dirty`

**Comment by troglobit** [comment]
Nice catch!  I'm guessing -x "hostname:infix-r2s-1" would work better, right?

**Comment by minexn** [comment]
Because the hostname doesn't contain spaces, we don't need quotation marks.

_RFCs mandate that a hostname's labels may contain only the ASCII letters 'a' through 'z' (case-insensitive), the digits '0' through '9', and the hyphen. Hostname labels cannot begin or end with a hyphen. No other symbols, punctuation characters, or blank spaces are permitted._

`udhcpc -f -p /run/dhcp-eth0.pid -t 10 -T 3 -A 10 -a1000 -S -R -x hostname:infix-r2s-1 -i eth0 -V Infix v23.11.0-121-g051658d-dirt`

**Comment by minexn** [comment]
Another fantastic fix for infix 👍
