### ISSUE TITLE
Do not run udev with debug

### ISSUE THREAD

**Issue by mattiaswal** [kernelkit/infix#305]
Spams (flood)  the log unnecessary. Specially when you have an USB attached.
From syslog:
<pre>
Feb 17 12:43:12 infix-00-00-00 kernel: usb 1-1: USB disconnect, device number 2
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: Validate module index
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2347 queued, 'remove' 'bsg'
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2347 forked new worker [2852]
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2347 running
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 245 byte device to netlink monitor 0x55986efb5810
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2347 processed
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2348 queued, 'remove' 'scsi_device'
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 218 byte device to netlink monitor 0x55986efada00
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2348 running
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: no db file to read /run/udev/data/+scsi_device:2:0:0:0: No such file or directory
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 216 byte device to netlink monitor 0x55986efb5810
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2348 processed
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2349 queued, 'remove' 'scsi_disk'
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 214 byte device to netlink monitor 0x55986efada00
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2349 running
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: no db file to read /run/udev/data/+scsi_disk:2:0:0:0: No such file or directory
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 212 byte device to netlink monitor 0x55986efb5810
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2349 processed
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2350 queued, 'remove' 'bdi'
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 139 byte device to netlink monitor 0x55986efada00
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2350 running
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: no db file to read /run/udev/data/+bdi:8:0: No such file or directory
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 137 byte device to netlink monitor 0x55986efb5810
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2350 processed
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: inotify event: 8000 for /dev/sda
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: removing watch on '/dev/sda'
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2351 queued, 'remove' 'block'
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 259 byte device to netlink monitor 0x55986efada00
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2351 running
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: removing watch on '/dev/sda'
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: no reference left, remove '/dev/disk/by-id/usb-QEMU_QEMU_HARDDISK_1-0000:00:09.0-1-0:0'
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: no reference left, remove '/dev/disk/by-path/pci-0000:00:09.0-usb-0:1:1.0-scsi-0:0:0:0'
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: no reference left, remove '/dev/disk/by-uuid/65D0-A9BC'
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 991 byte device to netlink monitor 0x55986efb5810
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2351 processed
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2352 queued, 'unbind' 'scsi'
Feb 17 12:43:12 infix-00-00-00 kernel: sd 2:0:0:0: [sda] Synchronizing SCSI cache
Feb 17 12:43:12 infix-00-00-00 kernel: sd 2:0:0:0: [sda] Synchronize Cache(10) failed: Result: hostbyte=0x01 driverbyte=DRIVER_OK
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 211 byte device to netlink monitor 0x55986efada00
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2352 running
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: no db file to read /run/udev/data/+scsi:2:0:0:0: No such file or directory
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 211 byte device to netlink monitor 0x55986efb5810
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2352 processed
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2353 queued, 'remove' 'scsi'
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 232 byte device to netlink monitor 0x55986efada00
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2353 running
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: no db file to read /run/udev/data/+scsi:2:0:0:0: No such file or directory
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 230 byte device to netlink monitor 0x55986efb5810
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2353 processed
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2354 queued, 'remove' 'scsi'
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 203 byte device to netlink monitor 0x55986efada00
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2354 running
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: no db file to read /run/udev/data/+scsi:target2:0:0: No such file or directory
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 201 byte device to netlink monitor 0x55986efb5810
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2354 processed
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2355 queued, 'remove' 'scsi_host'
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 192 byte device to netlink monitor 0x55986efada00
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2355 running
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: no db file to read /run/udev/data/+scsi_host:host2: No such file or directory
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 190 byte device to netlink monitor 0x55986efb5810
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2355 processed
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2356 queued, 'remove' 'scsi'
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 189 byte device to netlink monitor 0x55986efada00
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2356 running
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: no db file to read /run/udev/data/+scsi:host2: No such file or directory
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 187 byte device to netlink monitor 0x55986efb5810
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2356 processed
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2357 queued, 'remove' 'workqueue'
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 158 byte device to netlink monitor 0x55986efada00
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2357 running
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: no db file to read /run/udev/data/+workqueue:scsi_tmf_2: No such file or directory
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 156 byte device to netlink monitor 0x55986efb5810
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2357 processed
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2358 queued, 'unbind' 'usb'
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 231 byte device to netlink monitor 0x55986efada00
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2358 running
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: no db file to read /run/udev/data/+usb:1-1:1.0: No such file or directory
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 231 byte device to netlink monitor 0x55986efb5810
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2358 processed
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2359 queued, 'remove' 'usb'
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 290 byte device to netlink monitor 0x55986efada00
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2359 running
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: no db file to read /run/udev/data/+usb:1-1:1.0: No such file or directory
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 288 byte device to netlink monitor 0x55986efb5810
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2359 processed
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2360 queued, 'unbind' 'usb'
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 272 byte device to netlink monitor 0x55986efada00
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2360 running
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: IMPORT builtin 'usb_id' /lib/udev/rules.d/50-udev-default.rules:13
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: Error opening USB device 'descriptors' file: No such file or directory
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: No USB vendor information available
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: IMPORT builtin 'usb_id' returned non-zero
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: handling device node '/dev/bus/usb/001/002', devnum=c189:1, mode=0600, uid=0, gid=0
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: can not stat() node '/dev/bus/usb/001/002' (No such file or directory)
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: created empty file '/run/udev/data/c189:1' for '/devices/pci0000:00/0000:00:09.0/usb1/1-1'
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 271 byte device to netlink monitor 0x55986efb5810
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2360 processed
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2361 queued, 'remove' 'usb'
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 272 byte device to netlink monitor 0x55986efada00
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2361 running
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 270 byte device to netlink monitor 0x55986efb5810
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2361 processed
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2362 queued, 'unbind' 'usb'
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 228 byte device to netlink monitor 0x55986efada00
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2362 running
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: no db file to read /run/udev/data/+usb:1-0:1.0: No such file or directory
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 228 byte device to netlink monitor 0x55986efb5810
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2362 processed
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2363 queued, 'remove' 'usb'
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 287 byte device to netlink monitor 0x55986efada00
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2363 running
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: no db file to read /run/udev/data/+usb:1-0:1.0: No such file or directory
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 285 byte device to netlink monitor 0x55986efb5810
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2363 processed
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2364 queued, 'unbind' 'usb'
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 228 byte device to netlink monitor 0x55986efada00
Feb 17 12:43:12 infix-00-00-00 confd[2462]: [INF] EV LISTEN: "ietf-hardware" "done" ID 2 priority 65535 success (remaining 0 subscribers). 
Feb 17 12:43:12 infix-00-00-00 confd[2462]: [INF] EV LISTEN: "ietf-hardware" "done" ID 2 priority 64978 processing (remaining 1 subscribers). 
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2364 running
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: no db file to read /run/udev/data/+usb:2-0:1.0: No such file or directory
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 228 byte device to netlink monitor 0x55986efb5810
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2364 processed
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2365 queued, 'remove' 'usb'
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 287 byte device to netlink monitor 0x55986efada00
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2365 running
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: no db file to read /run/udev/data/+usb:2-0:1.0: No such file or directory
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: passed 285 byte device to netlink monitor 0x55986efb5810
Feb 17 12:43:12 infix-00-00-00 udevd[1188]: seq 2365 processed

</pre>

**Comment by troglobit** [comment]
I've noticed this too, I suggest we reduce the log level for udevd (and also sysrepo & C:o).
