### ISSUE TITLE
bootstrap: takes 10+ seconds on VLAN test config

### ISSUE THREAD

**Issue by troglobit** [kernelkit/infix#362]
Customer reports that the bootstrap phase takes >10 seconds when applying the attached [startup-config.cfg](https://github.com/kernelkit/infix/files/14760801/startup-config-cfg.txt) on a system with 29 ports and VLAN test config.

Related to:
 - #326

**Comment by troglobit** [comment]
@ CCB: Is this customer issue still a priority?

**Comment by wkz** [comment]
Yesterday, I got some info from the customer about the results of their compliance tests, where they originally used this setup. There was no mention of any issues with setting up the system.

Therefore, I suggest we close this.

**Comment by troglobit** [comment]
CCB agrees, closing.
