### ISSUE TITLE
Unable to disable DHCPv4 with "no dhcp-client"

### ISSUE THREAD

**Issue by jovatn** [kernelkit/infix#384]
Tested on latest build (2024-04-08) as well as infix 2024.02 release. 
This is a regression, as this has worked before.

If dhcp-v4 client is enabled, it no longer works to disable it using "no dhcp-client".

```
admin@infix-00-00-00:/> configure 
admin@infix-00-00-00:/config/> no dhcp-client 
Error: Can't apply changes
admin@infix-00-00-00:/config/> show dhcp-client 
enabled true;
client-if e0 {
  option broadcast
  option dns
  option domain
  option hostname
  option ntpsrv
  option router
  option subnet
}
admin@infix-00-00-00:/config/>
```

Looking at the syslog, it seems as if netopeer is restarted. Note, we have not even left configuration mode.

```
Apr  8 11:44:06 infix-00-00-00 finit[1]: Stopping netopeer[2542], sending SIGTERM ...
Apr  8 11:44:06 infix-00-00-00 finit[1]: Stopping statd[2475], sending SIGTERM ...
Apr  8 11:44:06 infix-00-00-00 finit[1]: Service confd[2372] died, restarting in 2000 msec (1/10)
Apr  8 11:44:06 infix-00-00-00 finit[1]: Starting confd[2718]

```

**Comment by troglobit** [comment]
I think I see the problem from the log `Service confd[2372] died`.  It's not supposed to die, at all (ever), so it seems disabling dhcp-client triggers a bug that crashes confd.
