### ISSUE TITLE
Upgrade netconf_client for tests and create a new docker image

### ISSUE THREAD

**Issue by mattiaswal** [kernelkit/infix#390]
This since they now have added get-data RPC which we have patched on our own.
infamy/netconf.py:
<pre>
 def _get_data(self, xpath,as_xml=False):
        """Local member wrapper for netconf-client <get-data> RPC"""
        # pylint: disable=protected-access
        (raw, ele) = self.ncc._send_rpc(self._ncc_get_data_rpc(filter=xpath))
        data = NccGetDataReply(raw, ele)
        if(as_xml):
            return data
</pre>
From netconf_client:
<pre>
add support for the < get-data > command from RFC 8526
</pre>

**Comment by troglobit** [comment]
Ah great, finally!
