### ISSUE TITLE
Creating VLAN interface with "edit interface vlan<N>" does not set VLAN id

### ISSUE THREAD

**Issue by jovatn** [kernelkit/infix#391]
When creating a VLAN interface with interface name convention "vlan<N>" we get interface "type vlan". But as a convenience the vlan id should also be set to N. (Compare with "edit interface eth1.N" which[ fills in both type and vlan id](https://github.com/kernelkit/infix/blob/main/doc/networking.md#vlan-interfaces))

```
admin@infix-00-00-00:/> configure
admin@infix-00-00-00:/config/> edit interface vlan10
admin@infix-00-00-00:/config/interface/vlan10/> show
type vlan;
admin@infix-00-00-00:/config/interface/vlan10/> set vlan id 10
admin@infix-00-00-00:/config/interface/vlan10/> show
type vlan;
vlan {
  id 10;
}
admin@infix-00-00-00:/config/interface/vlan10/> 
```

**Comment by troglobit** [comment]
For completeness, when using the CLI, the `set vlan id 10` should not be necessary since the system can "help out" by predicting the VLAN ID based on the interface name.
