### ISSUE TITLE
Generate list of supported YANG models for documentation

### ISSUE THREAD

**Issue by troglobit** [kernelkit/infix#432]
As discussed in #326, after the big refactor to offline, we could generate a list of supported YANG models, their features, as well as augments/deviations.

As an example, with only a few models, here's how to create a HTML/JavaScript page of IETF System:

    pyang -f jstree ietf-system@2014-08-06.yang infix-shell-type@2023-08-21.yang \
                    infix-system@2024-04-12.yang > infix-ietf-system.html

**Comment by troglobit** [comment]
Two alternatives:
 - trimmed output from tried-and-tested pyang: [output.html.gz](https://github.com/user-attachments/files/15948144/output.html.gz)
 - newcomer ytree: [ytree.html.gz](https://github.com/user-attachments/files/15948145/ytree.html.gz)

**Comment by jovatn** [comment]
Wow!
