### ISSUE TITLE
Integrate CESNET/rousette for RESTCONF support

### ISSUE THREAD

**Issue by troglobit** [kernelkit/infix#433]
For proper RESTCONF support with sysrepo we should add https://github.com/CESNET/rousette and its companion packages.  This would enable implementing a WebUI that can traverse the YANG tree and, similar to klish, create a default hierarchy of both configuration and operational state.  Specialized views, composing various YANG nodes, into logical setup/wizard like configuration is also possible.

> Depends on #326 since Rousette requires newer libyang + sysrepo.

**Comment by mattiaswal** [comment]
Done in #472
