### ISSUE TITLE
New users added to non-admin group still mapped to UNIX group 'wheel'

### ISSUE THREAD

**Issue by jovatn** [kernelkit/infix#469]
### Current Behavior

Creating a new user, and adding it to a non-admin group will result in the user being mapped to the privileged group 'wheel'.

Just creating the new user (jacky) will not give this result ...

```
admin@switch:/> configure 
admin@switch:/config/> edit system authentication user jacky
admin@switch:/config/system/authentication/user/jacky/> change password
New password: 
Retype password: 
admin@switch:/config/system/authentication/user/jacky/> set shell clish
admin@switch:/config/system/authentication/user/jacky/> leave
admin@switch:/> exit
admin@switch:~$ cat /etc/group
...
wheel:x:10:root,admin
...
admin:x:1000:
jacky:x:1001:
admin@switch:~$ 
```

... however, after adding jacky to a non-admin group (foobar), jacky ends up in the wheel group.

```
admin@switch:/> configure
admin@switch:/config/> edit nacm group foobar
admin@switch:/config/nacm/group/foobar/> set user-name jacky
admin@switch:/config/nacm/group/foobar/> leave
admin@switch:/> exit
admin@switch:~$ cat /etc/group
...
wheel:x:10:root,admin,jacky
...
admin:x:1000:
jacky:x:1001:
admin@switch:~$    
```

### Expected Behavior

Users should not be added to UNIX group 'wheel' unless they are added to NACM group 'admin'.

### Steps To Reproduce

1. Install Infix 24.04.2
2. Factory reset
3. Carry out commands as shown above.

**Comment by troglobit** [comment]
Reproduced, nice finding!

I believe this is the root cause also of #468.
