### ISSUE TITLE
test: Refactor xpath handling in netconf/restconf

### ISSUE THREAD

**Issue by mattiaswal** [kernelkit/infix#490]
> I'm approving this, because I'm not sure now much of my feedback is reasonable to
> address now, but please have a think about it.
> 
> Great to finally get to protocol parity on the test side of things! :clap: :clap:

_Originally posted by @wkz in https://github.com/kernelkit/infix/pull/484#pullrequestreview-2144428870_

**Comment by troglobit** [comment]
I'm assigning this to you, @mattiaswal, since you probably know what this is about, and assigning to the v24.08 milestone.

**Comment by mattiaswal** [comment]
> I'm assigning this to you, @mattiaswal, since you probably know what this is about, and assigning to the v24.08 milestone.

I failed dodging it :smile:
