### ISSUE TITLE
login: warning missing pam_lastlog.so

### ISSUE THREAD

**Issue by troglobit** [kernelkit/infix#542]
```
login[2819]: PAM unable to dlopen(/lib/security/pam_lastlog.so): /lib/security/pam_lastlog.so: cannot open shared object file: No such file or directory
```

**Comment by mattiaswal** [comment]
lastlog is not enabled in linux-pam in buildroot.
I think lastlog is a good thing, but --enable-lastlog needs to be added to buildroot recipe.

**Comment by troglobit** [comment]
Aha, time for some upstream work then!  I'll have a look :-)

**Comment by mattiaswal** [comment]
> Aha, time for some upstream work then! I'll have a look :-)

Please also upstream my patch on linux pam to fix path for .pc files when you are already on :fire:

**Comment by troglobit** [comment]
Ouch, that one looks a bit nasty, their pkg-config cross-build-wrapper seems to be hard coded to /usr/lib, but iirc there's a reason for certain packages to install to /lib ... could become a messy discussion, but sure I'll look into it at the same time.

**Comment by troglobit** [comment]
Upstream patch for `pam_lastlog.so` https://lore.kernel.org/buildroot/20240804095012.878259-1-troglobit@gmail.com/T/#u

**Comment by mattiaswal** [comment]
> ./output/host/bin/pkg-config --cflags pam

lazzer@tollan ~/Documents/addiva/infix (main)$ ./output/host/bin/pkg-config --cflags pam
Package pam was not found in the pkg-config search path.
Perhaps you should add the directory containing `pam.pc'
to the PKG_CONFIG_PATH environment variable
Package 'pam', required by 'virtual:world', not found
lazzer@tollan ~/Documents/addiva/infix (main)$

**Comment by mattiaswal** [comment]
How do your * find output/ -name.pc * looks like?

My (relevant parts) looks like:
<pre>
output/host/x86_64-buildroot-linux-gnu/sysroot/lib/pkgconfig/pamc.pc
output/host/x86_64-buildroot-linux-gnu/sysroot/lib/pkgconfig/pam.pc
output/host/x86_64-buildroot-linux-gnu/sysroot/lib/pkgconfig/pam_misc.pc
output/host/x86_64-buildroot-linux-gnu/sysroot/usr/lib/pkgconfig/dbus-cxx-2.0.pc
output/host/x86_64-buildroot-linux-gnu/sysroot/usr/lib/pkgconfig/libtirpc.pc
output/host/x86_64-buildroot-linux-gnu/sysroot/usr/lib/pkgconfig/libnetfilter_cthelper.pc
output/host/x86_64-buildroot-linux-gnu/sysroot/usr/lib/pkgconfig/libnetfilter_conntrack.pc
output/host/x86_64-buildroot-linux-gnu/sysroot/usr/lib/pkgconfig/libuev.pc
output/host/x86_64-buildroot-linux-gnu/sysroot/usr/lib/pkgconfig/ext2fs.pc
output/host/x86_64-buildroot-linux-gnu/sysroot/usr/lib/pkgconfig/avahi-core.pc
output/host/x86_64-buildroot-linux-gnu/sysroot/usr/lib/pkgconfig/libbsd.pc
output/host/x86_64-buildroot-linux-gnu/sysroot/usr/lib/pkgconfig/libpcre2-8.pc
output/host/x86_64-buildroot-linux-gnu/sysroot/usr/lib/pkgconfig/libsyslog.pc
output/host/x86_64-buildroot-linux-gnu/sysroot/usr/lib/pkgconfig/glib-2.0.pc
output/host/x86_64-buildroot-linux-gnu/sysroot/usr/lib/pkgconfig/popt.pc
output/host/x86_64-buildroot-linux-gnu/sysroot/usr/lib/pkgconfig/libassuan.pc
output/host/x86_64-buildroot-linux-gnu/sysroot/usr/lib/pkgconfig/sysrepo.pc
output/host/x86_64-buildroot-linux-gnu/sysroot/usr/lib/pkgconfig/libpcre2-posix.pc
output/host/x86_64-buildroot-linux-gnu/sysroot/usr/lib/pkgconfig/json-c.pc
.....
</pre>

**Comment by troglobit** [comment]
Interesting, here's my output, notably from Buildroot (recently branched from) master:

```bash
~/src/buildroot(linux-pam-options)$ find output/staging/ -name '*.pc'
output/staging/usr/lib/pkgconfig/libcrypt.pc
output/staging/usr/lib/pkgconfig/libxcrypt.pc
output/staging/usr/lib/pkgconfig/python-3.12-embed.pc
output/staging/usr/lib/pkgconfig/fmt.pc
output/staging/usr/lib/pkgconfig/python3.pc
output/staging/usr/lib/pkgconfig/libsyslog.pc
output/staging/usr/lib/pkgconfig/zlib.pc
output/staging/usr/lib/pkgconfig/pam.pc
output/staging/usr/lib/pkgconfig/pam_misc.pc
output/staging/usr/lib/pkgconfig/python3-embed.pc
output/staging/usr/lib/pkgconfig/spdlog.pc
output/staging/usr/lib/pkgconfig/python-3.12.pc
output/staging/usr/lib/pkgconfig/pamc.pc
output/staging/usr/lib/pkgconfig/expat.pc
output/staging/usr/lib/pkgconfig/openssl.pc
output/staging/usr/lib/pkgconfig/libssl.pc
output/staging/usr/lib/pkgconfig/libffi.pc
output/staging/usr/lib/pkgconfig/libcrypto.pc
```

Lemme have a look around the tree.

**Comment by troglobit** [comment]
Found it, root cause is:

```
# BR2_ROOTFS_MERGED_USR is not set
```

With it unset, as in Infix' defconfigs, I get the same as you:

```bash
~/src/buildroot(linux-pam-options)$ find output/staging/ -name '*.pc'
output/staging/usr/lib/pkgconfig/libcrypt.pc
output/staging/usr/lib/pkgconfig/libxcrypt.pc
output/staging/usr/lib/pkgconfig/python-3.12-embed.pc
output/staging/usr/lib/pkgconfig/python3.pc
output/staging/usr/lib/pkgconfig/libsyslog.pc
output/staging/usr/lib/pkgconfig/zlib.pc
output/staging/usr/lib/pkgconfig/python3-embed.pc
output/staging/usr/lib/pkgconfig/python-3.12.pc
output/staging/usr/lib/pkgconfig/expat.pc
output/staging/usr/lib/pkgconfig/openssl.pc
output/staging/usr/lib/pkgconfig/libssl.pc
output/staging/usr/lib/pkgconfig/libffi.pc
output/staging/usr/lib/pkgconfig/libcrypto.pc
output/staging/lib/pkgconfig/pam.pc
output/staging/lib/pkgconfig/pam_misc.pc
output/staging/lib/pkgconfig/pamc.pc
```

Since there's no point really in maintaining a difference beteen `/bin,/sbin` and `/usr/bin,/usr/sbin` et al on Infix, I suggest we update our defconfigs to:

```
BR2_ROOTFS_MERGED_USR=y
```

Which is the default, so dropping the line entirely would be equivalent.
