### ISSUE TITLE
Sort loopback first in show interfaces

### ISSUE THREAD

**Issue by troglobit** [kernelkit/infix#545]
I propose sorting interfaces in `show interfaces` such that `lo` is always displayed first. It is the only interface that all systems will have and also the order in which standard Linux/UNIX tools display interfaces. 

Consider even listing all interfaces in ifindex order.

**Comment by wkz** [comment]
Some thoughts:
- `lo` on top sounds good to me
- `ifindex` is roughly equivalent to the hardware probe order, which is rarely the most intuitive order to view stuff in. I don't think we want to rely on that when sorting

Today, we try convey interface hierarchy when possible (bridge ports are listed "under" their bridge, vlans are stacked on top of their lowers, etc). If we want to find some other sort order, we need to think about the implications on this feature. One option would be to have a separate command that lists interfaces with hierarchy indications, and that `show interfaces` outputs a flat table. In that case the sort key could be `iftype` (where we could rank loopbacks highest), with `ifname` as the tiebreaker within each type.

**Comment by troglobit** [comment]
Good point, I had forgotten about the weird probe order thing.

I think the current hierarchy view of `show interfaces` is great!  we already have `show ip [brief|detailed|multicast]` command, so maybe that's sufficient for all other use-cases?
