### ISSUE TITLE
Failure in bridge configuration lock sysrepo

### ISSUE THREAD

**Issue by mattiaswal** [kernelkit/infix#585]
Very easy to reproduce. I use qemu with 6 interfaces

<pre>
admin@infix-00-00-00:/> copy fa ru
admin@infix-00-00-00:/> configure 
admin@infix-00-00-00:/config/> set interface br1
admin@infix-00-00-00:/config/> set interface e3 bridge-port bridge br1
admin@infix-00-00-00:/config/> set interface br1 bridge vlans vlan 30 multicast-filter 224.2.2.2 ports e3
admin@infix-00-00-00:/config/> leave 
Error: EV ORIGIN: SHM event "done" ID 2 processing timed out.
Please check your changes, try 'diff' and 'do show interfaces'.
admin@infix-00-00-00:/config/> 
admin@infix-00-00-00:/config/> abort
admin@infix-00-00-00:/> reboot
Error: EV ORIGIN: SHM event "rpc" ID 1 processing timed out.
Error: failed sending RPC /ietf-system:system-restart: User callback failed
admin@infix-00-00-00:/> 
</pre>

This config is wrong (e3 does not exist in vlan 30) and should be blocked by a must expression, but still this feel fishy.

**Comment by mattiaswal** [comment]
Failed even with correct VLAN setting (e3 untagged).
If i do it in small steps it succeed. Configure one thing and leave.

**Comment by troglobit** [comment]
Reproduced. Have possible sysrepo fix in my tree.
