### ISSUE TITLE
New data forward test: verify bridge-port pvid and VLAN filtering

### ISSUE THREAD

**Issue by troglobit** [kernelkit/infix#59]

**Comment by wkz** [comment]
I suggest we leverage the kernel's forwarding test suite for this kind of dataplane verification.

**Comment by mattiaswal** [comment]
This is tested by igmp_vlan, is it enough @troglobit

**Comment by troglobit** [comment]
> This is tested by igmp_vlan, is it enough @troglobit

Yeah I think that's sufficient.
