### ISSUE TITLE
Update all tests for test specification

### ISSUE THREAD

**Issue by mattiaswal** [kernelkit/infix#606]
Test name, description, test.step() and the logical topology needs to be modified to that the final specification looks nice. In the testing.md it is described how to write them.

This is since the introduction of automatic generated test specification in #604

- [x] ietf-system (@mattiaswal)
- [x]  Merge infix-interfaces into ietf-interface (@mattiaswal)
- [x] ietf-interfaces (@mattiaswal)
- [x] ietf-hardware
- [x] ietf-routing (@mattiaswal)
- [x] ietf-syslog (@troglobit)
- [x] infix-containers (@troglobit)
- [x] infix-dhcp (@troglobit)
- [x] infix-services (@troglobit)
- [ ] meta
- [x] misc

**Comment by troglobit** [comment]
Assigning a few to myself.
