### ISSUE TITLE
Bump libyang, libnetconf2, netopeer2, sysrepo

### ISSUE THREAD

**Issue by troglobit** [kernelkit/infix#631]
New releases of core packages:

 - https://github.com/CESNET/libyang/releases/tag/v3.4.2
 - https://github.com/CESNET/libnetconf2/releases/tag/v3.5.1
 - https://github.com/CESNET/netopeer2/releases/tag/v2.2.31
 - https://github.com/sysrepo/sysrepo/releases/tag/v2.11.7

**Comment by mattiaswal** [comment]
Fixed in #637
