### ISSUE TITLE
Unauthorised can unlock/lock an USB port

### ISSUE THREAD

**Issue by mattiaswal** [kernelkit/infix#643]
Create a user, without any NACM permissions and he will still be able to enable/disable the USB port.

```
kalle@infix-00-00-00:/config/hardware/> set component USB state admin-state unlocked 
```
This leaf should be read only by default

**Comment by troglobit** [comment]
Propose changing titles -> Unauthorised users can ...

(Second A in AAA, you know ;-)

**Comment by mattiaswal** [comment]
My fault, it works as expected.
