### ISSUE TITLE
test: uninitalized node attributes warning

### ISSUE THREAD

**Issue by troglobit** [kernelkit/infix#660]
Very annoying bug/omission in physical topology.

```
$ make test-sh
Info: Generating topology
Info: Generating node YAML
gvpr: warning: Using value of uninitialized node attribute "qn_basemac" of "dut1"
gvpr: warning: Using value of uninitialized edge attribute "qn_headmac" of "dut1--dut2"
gvpr: warning: Using value of uninitialized edge attribute "qn_tailmac" of "dut1--dut2"
Info: Generating executables
Info: Launching dut1
Info: Launching dut2
Info: Launching dut3
Info: Launching dut4
```

**Comment by ahmkar94** [comment]
The warnings have been resolved in the `qeneth` project. Integration/Review is pending @wkz , allowing the correct revision to be referenced.

**Comment by troglobit** [comment]
Nice work!  (For future reference, it's really helpful if you drop a link to projects outside of the issue you report in :)

**Comment by troglobit** [comment]
I see @wkz merged this tonight.  Please post a submodule update as well so we can close this issue properly :-)
