### ISSUE TITLE
CLI: Internal ports are shown in tab completion

### ISSUE THREAD

**Issue by mattiaswal** [kernelkit/infix#663]
The DSA port is internal, no use for the user, should not be seen when tab complete.

<pre>
admin@test-06-07-00:/> show interfaces name 
dsa0  lo   x1  x10   x2   x3   x4   x5   x6   x7   x8   x9
admin@test-06-07-00:/> show interfaces name 
</pre>
This is no regression it is seen as early as 24.06

**Comment by troglobit** [comment]
Issue introduced already in July, 2023.
