### ISSUE TITLE
test: extend bridge-vlan-separation with MAC broadcast traffic

### ISSUE THREAD

**Issue by troglobit** [kernelkit/infix#773]
The test `ietf_interfaces/bridge_vlan_separation` currently only use IP traffic, so a background load of broadcast (or multicast without IGMP/MLD snooping) traffic should be added.

Requirements:

 - At least two VLANs
 - At least two DUTs with a VLAN trunk between them
 - Verify IP connectivity and isolation
 - Verify MAC traffic isolation (see suggestion below)

My (@jovatn) suggestion for MAC traffic isolation would be to send some layer-2 broadcast and check that it reaches within the senders VLAN but not across to another VLAN.
Layer-2 broadcast could be achieved by pinging subnet broadcast (say "ping -b 10.0.0.255" on 10.0.0.0/24) or by ARP broadcast.

**Comment by jovatn** [comment]
My 2 cents.
My suggestion for MAC traffic isolation would be to send some layer-2 broadcast and check that it reaches within the senders VLAN but not across to another VLAN. 
Layer-2 broadcast could be achieved by  pinging subnet broadcast (say "ping -b 10.0.0.255" on 10.0.0.0/24) or by ARP broadcast.
